"""add_timestamps

Revision ID: e3beda372c60
Revises: 75f6b9dd8255
Create Date: 2025-09-23 13:41:04.647436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3beda372c60'
down_revision: Union[str, None] = '75f6b9dd8255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('doctor', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('doctor', 'time_created')
    op.drop_column('doctor', 'time_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('doctor', sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('doctor', 'updated_at')
    op.drop_column('doctor', 'created_at')
    # ### end Alembic commands ###
