"""add_timestamps

Revision ID: ae83b278cadf
Revises: e3beda372c60
Create Date: 2025-09-23 15:55:59.597182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae83b278cadf'
down_revision: Union[str, None] = 'e3beda372c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('doctor', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('doctor', 'image_path')
    # ### end Alembic commands ###
