"""init

Revision ID: c7c77c139577
Revises: 
Create Date: 2025-09-25 03:31:06.878780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c77c139577'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discounted_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'child', 'general', name='gender_enum'), nullable=True),
    sa.Column('checkup_type', sa.Enum('first', 'secondary', 'third', name='checkuptype'), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkup_id'), 'checkup', ['id'], unique=False)
    op.create_table('contact_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_request_id'), 'contact_request', ['id'], unique=False)
    op.create_table('departament',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departament_id'), 'departament', ['id'], unique=False)
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('consultation_cost', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('profile_treatment', sa.Text(), nullable=False),
    sa.Column('work_experience', sa.Text(), nullable=False),
    sa.Column('education', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('online_booking_link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_id'), 'doctor', ['id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_table('speciality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speciality_id'), 'speciality', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speciality_id'), table_name='speciality')
    op.drop_table('speciality')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_doctor_id'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_departament_id'), table_name='departament')
    op.drop_table('departament')
    op.drop_index(op.f('ix_contact_request_id'), table_name='contact_request')
    op.drop_table('contact_request')
    op.drop_index(op.f('ix_checkup_id'), table_name='checkup')
    op.drop_table('checkup')
    # ### end Alembic commands ###
