"""Initial

Revision ID: af0946d0ab45
Revises: 8e1b740bbb13
Create Date: 2025-09-25 07:32:36.519299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af0946d0ab45"
down_revision: Union[str, None] = "8e1b740bbb13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "checkup",
        sa.Column(
            "gender",
            sa.Enum("male", "female", "child", "general", name="gender_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "checkup",
        sa.Column(
            "checkup_type",
            sa.Enum("first", "secondary", "third", name="checkuptype"),
            nullable=True,
        ),
    )

    op.execute(
        sa.text(
            "UPDATE checkup SET checkup_type = 'third' WHERE checkup_type IS NULL"
        )
    )

    op.alter_column(
        "checkup",
        "expired_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.String(length=256),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checkup",
        "expired_at",
        existing_type=sa.String(length=256),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_column("checkup", "checkup_type")
    op.drop_column("checkup", "gender")
    # ### end Alembic commands ###
