"""add_timestamps

Revision ID: 75f6b9dd8255
Revises: 1d602a01398f
Create Date: 2025-09-23 13:35:50.419493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f6b9dd8255'
down_revision: Union[str, None] = '1d602a01398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('doctor', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'time_updated')
    op.drop_column('doctor', 'time_created')
    # ### end Alembic commands ###
