"""

Revision ID: e044917c295c
Revises: 0df29d2ef29b
Create Date: 2025-09-23 19:54:27.261778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e044917c295c'
down_revision: Union[str, None] = '0df29d2ef29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('doctor', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('doctor', 'image_url')
    # ### end Alembic commands ###
