"""

Revision ID: 0e5d63524ad5
Revises: af0946d0ab45
Create Date: 2025-09-25 07:51:16.287960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e5d63524ad5'
down_revision: Union[str, None] = 'af0946d0ab45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkup', 'checkup_type',
               existing_type=postgresql.ENUM('first', 'secondary', 'third', name='checkuptype'),
               nullable=False)
    op.alter_column('checkup', 'expired_at',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('checkup', 'discount_percentage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkup', 'discount_percentage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('checkup', 'expired_at',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('checkup', 'checkup_type',
               existing_type=postgresql.ENUM('first', 'secondary', 'third', name='checkuptype'),
               nullable=True)
    # ### end Alembic commands ###
