"""add_some_tables

Revision ID: 1d602a01398f
Revises: 
Create Date: 2025-09-23 07:13:19.488294

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d602a01398f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("checkup",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_checkup_id"), "checkup", ["id"], unique=True)
    op.create_table("contact_request",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_contact_request_id"), "contact_request", ["id"], unique=True)
    op.create_table("departament",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_departament_id"), "departament", ["id"], unique=True)
    op.create_table("doctor",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("full_name", sa.String(), nullable=False),
    sa.Column("experience_years", sa.Integer(), nullable=False),
    sa.Column("consultation_cost", sa.Integer(), nullable=True),
    sa.Column("category", sa.String(), nullable=False),
    sa.Column("profile_treatment", sa.String(), nullable=False),
    sa.Column("work_experience", sa.String(), nullable=False),
    sa.Column("education", sa.String(), nullable=False),
    sa.Column("image_url", sa.String(), nullable=True),
    sa.Column("online_booking_link", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_doctor_id"), "doctor", ["id"], unique=True)
    op.create_table("service",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_service_id"), "service", ["id"], unique=True)
    op.create_table("speciality",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_speciality_id"), "speciality", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_speciality_id"), table_name="speciality")
    op.drop_table("speciality")
    op.drop_index(op.f("ix_service_id"), table_name="service")
    op.drop_table("service")
    op.drop_index(op.f("ix_doctor_id"), table_name="doctor")
    op.drop_table("doctor")
    op.drop_index(op.f("ix_departament_id"), table_name="departament")
    op.drop_table("departament")
    op.drop_index(op.f("ix_contact_request_id"), table_name="contact_request")
    op.drop_table("contact_request")
    op.drop_index(op.f("ix_checkup_id"), table_name="checkup")
    op.drop_table("checkup")
    # ### end Alembic commands ###
